# Generated by Django 3.1 on 2020-09-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
    ]
